# ===============================================
# Persistence Redis Adapter Configuration
# ===============================================

# Common Redis Settings
spring:
  # Exclude Redisson Spring Boot Starter auto-configuration
  # We use custom RedissonConfig instead
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2

  data:
    redis:
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4
          max-wait: 3000ms

---
# ===============================================
# Production Profile
# ===============================================
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

# Enable Redisson for distributed locking in production
redisson:
  enabled: true

---
# ===============================================
# Test Profile
# ===============================================
spring:
  config:
    activate:
      on-profile: test

  data:
    redis:
      host: localhost
      port: 6379
      password:

# Disable Redisson in test environment (no Redis needed)
redisson:
  enabled: false
