# ========================================
# SQS Listener Configuration (Default/Production)
# ========================================
# Spring Cloud AWS SQS configuration
# Environment variables are injected via ECS Task Definition
# ========================================

spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      sqs:
        # SQS 리스너 기본 설정
        listener:
          max-concurrent-messages: 10
          max-messages-per-poll: 10

aws:
  sqs:
    listener:
      # ========================================
      # Queue URLs (from Terraform SSM Parameters)
      # ========================================
      # ExternalDownload Queue: receives download tasks
      external-download-queue-url: ${SQS_EXTERNAL_DOWNLOAD_QUEUE_URL:}

      # ExternalDownload DLQ: receives failed tasks for error handling
      external-download-dlq-url: ${SQS_EXTERNAL_DOWNLOAD_DLQ_URL:}

      # FileProcessing Queue: receives file processing tasks (image resizing)
      file-processing-queue-url: ${SQS_FILE_PROCESSING_QUEUE_URL:}

      # FileProcessing DLQ: receives failed file processing tasks
      file-processing-dlq-url: ${SQS_FILE_PROCESSING_DLQ_URL:}

      # ========================================
      # Feature Toggles
      # ========================================
      # Enable/Disable individual listeners (configurable per bootstrap module)
      external-download-listener-enabled: ${EXTERNAL_DOWNLOAD_LISTENER_ENABLED:true}
      external-download-dlq-listener-enabled: ${EXTERNAL_DOWNLOAD_DLQ_LISTENER_ENABLED:true}
      file-processing-listener-enabled: ${FILE_PROCESSING_LISTENER_ENABLED:true}
      file-processing-dlq-listener-enabled: ${FILE_PROCESSING_DLQ_LISTENER_ENABLED:true}

logging:
  level:
    com.ryuqq.fileflow.adapter.in.sqs: INFO
    io.awspring.cloud.sqs: INFO
