# ============================================================================
# FILEFLOW - ECS Service
# ============================================================================
# Generated by Infrastructure Wizard
# Service: fileflow
# Environment: prod
# ============================================================================

# CloudWatch Log Group
module "fileflow_logs" {
  source = "../../modules/cloudwatch-log-group"

  name              = local.log_group_name
  retention_in_days = local.log_retention_days
  kms_key_id        = data.aws_kms_key.cloudwatch_logs.arn

  # Required tags
  environment = local.environment
  service     = local.service_name
  team        = "platform-team"
  owner       = "platform-team@example.com"
  cost_center = "engineering"
  project     = "fileflow"
}

# Security Group for ECS Tasks
resource "aws_security_group" "fileflow" {
  name_prefix = "${local.name_prefix}-ecs-"
  description = "Security group for fileflow ECS tasks"
  vpc_id      = local.vpc_id

  # Egress: Allow all outbound traffic
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound traffic"
  }

  # Ingress: Allow traffic from ALB
  ingress {
    from_port       = local.container_port
    to_port         = local.container_port
    protocol        = "tcp"
    security_groups = [aws_security_group.fileflow_alb.id]
    description     = "Allow traffic from ALB"
  }

  tags = merge(
    local.required_tags,
    {
      Name      = "sg-${local.name_prefix}-ecs"
      Component = "security"
    }
  )

  lifecycle {
    create_before_destroy = true
  }
}

# IAM Role for ECS Task Execution
resource "aws_iam_role" "fileflow_execution_role" {
  name = "${local.name_prefix}-ecs-execution-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "ecs-tasks.amazonaws.com"
      }
    }]
  })

  tags = local.required_tags
}

resource "aws_iam_role_policy_attachment" "fileflow_execution_role_policy" {
  role       = aws_iam_role.fileflow_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

# IAM Role for ECS Task
resource "aws_iam_role" "fileflow_task_role" {
  name = "${local.name_prefix}-ecs-task-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "ecs-tasks.amazonaws.com"
      }
    }]
  })

  tags = local.required_tags
}

# ECS Service
module "fileflow_service" {
  source = "../../modules/ecs-service"

  # Required variables
  name               = local.service_name
  cluster_id         = aws_ecs_cluster.fileflow.id
  container_name     = local.container_name
  container_port     = local.container_port
  container_image    = "nginx:latest"
  cpu                = 1024
  memory             = 2048
  desired_count      = 1
  execution_role_arn = aws_iam_role.fileflow_execution_role.arn
  task_role_arn      = aws_iam_role.fileflow_task_role.arn
  subnet_ids         = local.private_subnet_ids
  common_tags        = local.required_tags

  # Security groups
  security_group_ids = [aws_security_group.fileflow.id]

  # CloudWatch Logs
  log_configuration = {
    log_driver = "awslogs"
    options = {
      "awslogs-group"         = module.fileflow_logs.log_group_name
      "awslogs-region"        = "ap-northeast-2"
      "awslogs-stream-prefix" = "ecs"
    }
  }

  # Load Balancer Configuration
  load_balancer_config = {
    target_group_arn = module.fileflow_alb.target_group_arns["fileflow"]
    container_name   = local.container_name
    container_port   = local.container_port
  }

  # Environment Variables
  container_environment = [
    {
      name  = "ENVIRONMENT"
      value = local.environment
    },
    {
      name  = "SERVICE_NAME"
      value = local.service_name
    },
    {
      name  = "DB_HOST"
      value = local.db_address
    },
    {
      name  = "DB_PORT"
      value = tostring(local.db_port)
    }
  ]

  # Secrets (injected at runtime)
  container_secrets = [
    {
      name      = "DB_PASSWORD"
      valueFrom = data.aws_ssm_parameter.master_password_secret_name.value
    }
  ]

  depends_on = [
    module.fileflow_logs,
    aws_iam_role_policy_attachment.fileflow_execution_role_policy
  ]
}
