# ============================================================================
# FILEFLOW - ECS Service
# ============================================================================
# Generated by Infrastructure Wizard
# Service: fileflow
# Environment: prod
# ============================================================================

# CloudWatch Log Group
module "fileflow_logs" {
  source = "../../modules/cloudwatch-log-group"

  name              = local.log_group_name
  retention_in_days = local.log_retention_days
  kms_key_id        = data.aws_kms_key.cloudwatch_logs.arn

  tags = merge(
    local.required_tags,
    {
      Name      = "logs-${local.name_prefix}"
      Component = "logging"
    }
  )
}

# Security Group for ECS Tasks
resource "aws_security_group" "fileflow" {
  name_prefix = "${local.name_prefix}-ecs-"
  description = "Security group for fileflow ECS tasks"
  vpc_id      = local.vpc_id

  # Egress: Allow all outbound traffic
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow all outbound traffic"
  }

  # Ingress: Allow traffic from ALB
  ingress {
    from_port       = local.container_port
    to_port         = local.container_port
    protocol        = "tcp"
    security_groups = [aws_security_group.fileflow_alb.id]
    description     = "Allow traffic from ALB"
  }

  tags = merge(
    local.required_tags,
    {
      Name      = "sg-${local.name_prefix}-ecs"
      Component = "security"
    }
  )

  lifecycle {
    create_before_destroy = true
  }
}

# ECS Service
module "fileflow_service" {
  source = "../../modules/ecs-service"

  # Service Configuration
  service_name   = local.service_name
  environment    = local.environment
  cpu            = 1024
  memory         = 2048
  desired_count  = 1

  # Container Configuration
  container_name = local.container_name
  container_port = local.container_port
  container_image = "nginx:latest"

  # Network Configuration
  vpc_id             = local.vpc_id
  private_subnet_ids = local.private_subnet_ids
  security_group_ids = [aws_security_group.fileflow.id]

  # Logging Configuration
  log_group_name  = module.fileflow_logs.name
  log_region      = "ap-northeast-2"

  # Load Balancer Configuration
  target_group_arn = module.fileflow_alb.target_group_arn

  # Health Check
  health_check_path = ""

  # Environment Variables
  environment_variables = {
    ENVIRONMENT = local.environment
    SERVICE_NAME = local.service_name
    DB_HOST = local.db_address
    DB_PORT = local.db_port
  }

  # Secrets (injected at runtime)
  secrets = {
    DB_PASSWORD = data.aws_ssm_parameter.master_password_secret_name.value
  }

  tags = merge(
    local.required_tags,
    {
      Name      = "ecs-${local.name_prefix}"
      Component = "compute"
    }
  )

  depends_on = [
    module.fileflow_logs
  ]
}
