# ============================================================
# Persistence Layer 스테이지 환경 설정
# ============================================================
# 활성화: bootstrap의 application-stage.yml에서 import
# 운영과 유사하지만 디버깅 편의를 위해 일부 설정 완화
# ============================================================

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=true&requireSSL=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      # Pool Size (스테이지: 운영보다 작게)
      maximum-pool-size: 10
      minimum-idle: 5

      # Timeout
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

      # Leak Detection (스테이지: 활성화)
      leak-detection-threshold: 60000

      pool-name: HikariPool-Stage

      # Connection Health Check
      connection-init-sql: SELECT 1

      # MySQL 최적화
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  flyway:
    # 스테이지에서 clean 금지
    clean-disabled: true

logging:
  level:
    com.ryuqq.fileflow: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: WARN
