# ===============================================
# REST API Adapter Configuration - Production Profile
# ===============================================
spring:
  config:
    activate:
      on-profile: prod

# API Settings for Production
api:
  error:
    include-stacktrace: false

# Security Settings for Production
security:
  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGINS:https://fileflow.ryuqq.com}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Request-ID
      - X-Correlation-ID
    allow-credentials: true

  # Gateway Authentication
  gateway:
    enabled: true

  # Cookie Security Settings
  cookie:
    secure: true
    http-only: true
    same-site: strict
