name: Sync GitHub Issue to Jira

on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira Issue
        if: github.event.action == 'opened'
        id: create
        continue-on-error: true
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ secrets.JIRA_PROJECT_KEY }}
          issuetype: Task
          summary: "[GH-${{ github.event.issue.number }}] ${{ github.event.issue.title }}"
          description: |
            *Synced from GitHub Issue:* ${{ github.event.issue.html_url }}

            h3. Description
            ${{ github.event.issue.body || 'No description provided' }}

            ---
            *Created by:* ${{ github.event.issue.user.login }}
            *Labels:* ${{ join(github.event.issue.labels.*.name, ', ') || 'None' }}
            *GitHub Issue Number:* #${{ github.event.issue.number }}

      - name: Log Jira Creation Result
        if: github.event.action == 'opened'
        run: |
          echo "Jira issue creation outcome: ${{ steps.create.outcome }}"
          echo "Jira issue key: ${{ steps.create.outputs.issue }}"

      - name: Add Jira Issue Key to GitHub Issue
        if: github.event.action == 'opened' && steps.create.outputs.issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const jiraKey = '${{ steps.create.outputs.issue }}';
            const jiraUrl = '${{ secrets.JIRA_BASE_URL }}';
            
            console.log(`Created Jira issue: ${jiraKey}`);
            
            // Add comment with Jira link
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✅ Jira 이슈가 생성되었습니다: [${jiraKey}](${jiraUrl}/browse/${jiraKey})`
            });
            
            // Add label to track sync
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['jira-synced']
            });

      - name: Handle Jira Creation Failure
        if: github.event.action == 'opened' && steps.create.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `⚠️ Jira 이슈 생성에 실패했습니다. Jira 설정을 확인해주세요.\n\n` +
                    `다음 항목을 확인하세요:\n` +
                    `- JIRA_BASE_URL, JIRA_USER_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY Secrets 설정\n` +
                    `- Jira 프로젝트 권한\n` +
                    `- Issue Type이 프로젝트에서 사용 가능한지 확인`
            });
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['jira-sync-failed']
            });

      - name: Find Jira Issue from Comments
        if: github.event.action != 'opened'
        id: find
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Searching for Jira issue key in issue #${context.issue.number}`);
            
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            console.log(`Found ${comments.data.length} comments`);
            
            // Find Jira issue key from comments (matches both [KEY-123] and [KEY-123](url))
            const jiraKeyRegex = /\[([A-Z]+-\d+)\](?:\([^\)]+\))?/;
            const simpleKeyRegex = /([A-Z]+-\d+)/;
            
            for (const comment of comments.data) {
              console.log(`Checking comment by ${comment.user.login}: ${comment.body.substring(0, 100)}`);
              
              // First try to find in markdown link format
              let match = comment.body.match(jiraKeyRegex);
              if (match) {
                core.setOutput('issue', match[1]);
                console.log(`✅ Found Jira issue in markdown link: ${match[1]}`);
                return;
              }
              
              // If bot comment, try simple format
              if (comment.user.type === 'Bot' || comment.user.login.includes('[bot]')) {
                match = comment.body.match(simpleKeyRegex);
                if (match) {
                  core.setOutput('issue', match[1]);
                  console.log(`✅ Found Jira issue in bot comment: ${match[1]}`);
                  return;
                }
              }
            }
            
            // Also check issue title for [KEY-123] format
            console.log(`Checking issue title: ${context.payload.issue.title}`);
            const titleMatch = context.payload.issue.title.match(simpleKeyRegex);
            if (titleMatch) {
              core.setOutput('issue', titleMatch[1]);
              console.log(`✅ Found Jira issue in title: ${titleMatch[1]}`);
            } else {
              console.log('❌ No Jira issue key found');
              core.warning('Jira issue key not found. The issue may not have been synced initially.');
            }

      - name: Update Jira Issue Status (Closed)
        if: github.event.action == 'closed' && steps.find.outputs.issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: "Done"

      - name: Update Jira Issue Status (Reopened)
        if: github.event.action == 'reopened' && steps.find.outputs.issue
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: "To Do"

      - name: Add Comment to Jira
        if: github.event_name == 'issue_comment' && steps.find.outputs.issue
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          comment: |
            GitHub Comment by ${{ github.event.comment.user.login }}:
            
            ${{ github.event.comment.body }}
            
            [View on GitHub](${{ github.event.comment.html_url }})
